### ISSUE TITLE
单卡验证模型是出现问题

### ISSUE THREAD

**Issue by lion-liang** [xialuxi/yolox-yolov5#1]
训练模型后，到验证阶段出现如下错误。

evaluators/yolo_evaluator.py", line 169, in evaluate
    if d.item() not in detected_set:
       │ │             └ {0, 1, 2}
       │ └ <method 'item' of 'torch._C._TensorBase' objects>
       └ <unprintable Tensor object>

RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

**Comment by xialuxi** [comment]
查看配置文件 yolox_yolo_s.py中的self.num_classes 是否和你的数据匹配。
或者更新代码。

**Comment by lion-liang** [comment]
num_classes与数据类别数是一致的，能正常训练，只是在验证时出现上述错误。
