### ISSUE TITLE
Assertion error at training time

### ISSUE THREAD

**Issue by Md-Ferdous** [xialuxi/yolox-yolov5#2]
![image](https://user-images.githubusercontent.com/55968913/128629143-ed0f0a54-b56d-4ab7-9e92-08aafe9cc448.png)

**Comment by xialuxi** [comment]
Please debug your code。

**Comment by Md-Ferdous** [comment]
I try to find output metrics like YOLOv5 metrics e.g. precision-recall curve, confusion matrix, etc. I thought this repository will help me. I followed your steps, but I found this type of error. So, how can feed my dataset into YOLOX like YOLOv5?
